### ISSUE TITLE
Types: Ensure correct db is passed

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/spark-stats#153]
When passing a `pgPool` to a function, we need to ensure the right one is passed - the one for stats db, or for evaluate db. Can we secure this through types? Eg can we introduce a type `PgPoolEvaluate` that is the same as `PgPool`, but not interchangeable with `PgPoolStats`?

@bajtos assigning this to you for your expertise, but happy to look into this myself as well.

**Comment by bajtos** [comment]
Hmm, that's a great idea! This is what comes to my mind:

```ts
export interface PgPoolEvaluate extends pg.Pool {
  db: 'evaluate'
}

export interface PgPoolStats extends pg.Pool {
  db: 'stats'
}

export type PgPool =
 | PgPoolEvaluate
 | PgPoolStats
```

See https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions

Playground:
https://www.typescriptlang.org/play/?#code/HYQwtgpgzgDiDGEAEMDmSDeAoJvcQA8YB7AJwBcl4AbEKKJABWOOswF8tOtCSKkAlsHIRSAMwTJGqZqwCiANxDUAriBFJCI4ABMGaAHSy22XDoBGALiQByCEtXqINrlh5EylISPGSmMlmoAZXJ1Bi0IXX1UI0DMHCQLaxsoUPIoF25eTyRyAE8YKQDWJABeHAAff2NFZTURSurAkLC3MRVgeHIBYmAkAEcVUTyW9OMACjRja2ljUagASkwkbgB6VaQAFQALAX0QfgB3AWo2c2RyUgF4AGs83OIkVAhKK9RtymPybaQAKSCACLEeC5ArIEDAYDENI9YAMAC0SCh3UQSAARHQqL1UmjchBTkJ0Fh1lswUF4FcYJRvupMElbPY6k4bOwqKQIE4GBCkMRzAArCBdJBfH4gFCkYiFCj3YhiUGFBkOerOAzEjYAIXuOggEhU1HIABpbBYbOLJaJ8khtpj8gqUpdCabxspqMRDlzSOYBJcDvdUldgOgldAFqr4NjKIzHCJpk15EqnGUkAB5fmC8gGOhQASoYDjYAQQ4oGITBZGjCJKyKpkiFlITHhuHkBZuQbDeYTKPK4wt1YAKiQAD1B0gAGIgE4MEW5bbIMSsV3HQOaUgS0iWNwAQVIqBUkGEPLltuQNlmgVq0ecggYyPr9BzoHM1AujzgpHAL1Eh-lJ7PrHmNiqrgmxggwspmlKlo2Ca9bsoInTEGAcDdE+ECqgkwFgrYaJdk4aKmnsSLQne2a5iAqEPD+2GpGE+FAX2qxAA

**Comment by juliangruber** [comment]
Great, thank you!

Do you know how to convert a `PgPool` to a `PgPoolStats`?

```
/**
 * @returns {Promise<PgPoolStats>}
 */
export const getStatsPgPool = async () => {
  const stats = new pg.Pool({
    ...poolConfig,
    connectionString: DATABASE_URL
  })
  stats.db = 'stats' // .db doesn't exist in type
  stats.on('error', onError)
  await migrateStatsDB(stats)
  return stats 
}
```

**Comment by bajtos** [comment]
See the playground I shared:

```ts
// This part will be tricky to get right with JSDoc type annotations - notice "as const" telling 
// TypeScript that {db: 'evaluate'} creates an object with a property of type 'evaluate'.
// By default, 'db' property has type 'string' (allows arbitrary string values).
const evaluatePool: PgPoolEvaluate = Object.assign(new pg.Pool(), { db: 'evaluate'} as const)
```

In the worst case, you can cast to `any`.

```js
/** @type {PgPoolStats} */
const stats = /** @type {any} */(
  Object.assign(
    new pg.Pool({
      ...poolConfig,
      connectionString: DATABASE_URL
    }),
    { db: 'stats' }
  )
)
```

This could be a slightly cleaner solution, as it constrains the unchecked `any` code just to the type conversion from `pg.Pool & {db: string}` to `pg.Pool & {db: T}`, but I don't know if it will work with the JSDoc comments:

```js
/**
 * @template {DB}
 * @param {T} db
 * @param {pg.Pool} pgPool
 * @returns {PgPool & {db: T}}
 */
function getNamedPool(db, pgPool) {
  return /** @type {any} */(Object.assign(pgPool, {db}))
}

// usage
const stats = getNamedPool('stats', new pg.Pool({
  // ...
})
```

**Comment by bajtos** [comment]
Oooh, I found something.

https://stackoverflow.com/a/64687300/69868

Can you try this? 👇🏻 

```
/** @type {PgPoolEvaluate} */
const evaluatePool = Object.assign(
  new pg.Pool(), 
  /** @type {const} */({ db: 'evaluate' })
)
```

On second thought, the `getNamedPool` helper shown in my previous comment is probably easier to use and makes the code using that helper easier to read & understand compared to the code snippet in this commit, so it may be a better option.

**Comment by juliangruber** [comment]
<img width="442" alt="Screenshot 2024-07-15 at 18 19 52" src="https://github.com/user-attachments/assets/1e0fe61c-e6cd-4fd2-8b14-91cbb30fa812">

about the helper function

**Comment by juliangruber** [comment]
<img width="587" alt="Screenshot 2024-07-15 at 18 21 11" src="https://github.com/user-attachments/assets/71035711-376a-47dc-a8e7-b2c57c8b6ba8">

This also doesn't seem to work

**Comment by juliangruber** [comment]
similar:

<img width="626" alt="Screenshot 2024-07-15 at 18 22 10" src="https://github.com/user-attachments/assets/5ff2ff91-425e-4586-9372-b7bc70fe2ce7">

**Comment by bajtos** [comment]
@juliangruber could you please open a draft PR with the change you have tried, so that I can try to fix the types?

I think I have a bug in one of the examples above - the template and the param type should use the same name, either `DB` or `T`.

```js
/**
 * @template {DB}
 * @param {DB} db
 * @param {pg.Pool} pgPool
 * @returns {PgPool & {db: DB}}
 */
function getNamedPool(db, pgPool) {
  return /** @type {any} */(Object.assign(pgPool, {db}))
}
```

I am also not entirely sure about the syntax, maybe the template arg name should not be in curly braces.

```js
/**
 * @template DB
 * @param {DB} db
 * @param {pg.Pool} pgPool
 * @returns {PgPool & {db: DB}}
 */
function getNamedPool(db, pgPool) {
  return /** @type {any} */(Object.assign(pgPool, {db}))
}
```

**Comment by juliangruber** [comment]
Good idea! Here you go: https://github.com/filecoin-station/spark-stats/pull/185
The second `getNamedPool` seems to be the right syntax

**Comment by bajtos** [comment]
Closing as done by #185.
